services:
    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: inventorydb
        ports:
            - "5432:5432"