version: "3.8"

services:
    postgres:
        image: postgres:15
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: inventorydb
        ports:
            - "5432:5432"

    kafka:
        image: confluentinc/cp-kafka:7.4.0
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,HOST://localhost:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
            ["9092:9092", "29092:29092"]
    
    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        environment:
            ZOOKEPER_CLIENT_PORT: 2181

    redis:
        image: redis:7
        ports: ["6379:6379"]
    
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - monitoring
    
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        networks:
            - monitoring

networks:
    monitoring:
        driver: bridge